---
driver:
  name: ec2
  aws_ssh_key_id: chef_demo_2x
  region: us-west-2
  security_group_ids: sg-0b2281a349166fc6a
  subnet_id: subnet-06a3afbc3edb2b6e0
  associate_public_ip: true
  instance_type: m3.medium ##t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Chef Training Node for <YOURNAME>, Rees"
    created-by: "test-kitchen"
    user: administrator
    X-Contact: "Anthony Rees"
    X-Application: "APAC"
    X-Dept: "Sales"
    X-Customer: "Rees"
    X-Project: "BJC-Demo"
    X-Termination-Date: "2020-07-20T12:04:30Z"
    TTL: 20
    X-TTL: 20
    
transport:
    username: administrator
    ssh_key:  ~\.ssh\id_rsa
    communicator: winrm

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.3

verifier:
  name: inspec
  format: documentation

platforms:
  - name: windows-2012r2
# - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[myiis::server]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
