---
driver:
  name: ec2
  aws_ssh_key_id: chef_demo_2x
  region: us-west-2
  security_group_ids: sg-0b25db61aa0a1b487
  subnet_id: subnet-03dfd3f8e97a2a5ff
  associate_public_ip: true
  instance_type: m3.medium ##t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Chef Training Node for <YOURNAME>, Rees"
    created-by: "test-kitchen"
    user: administrator
    X-Contact: <%= ENV['USER'] %>
    X-Application: <%= ENV['X_APPLICATION'] %>
    X-Customer: "Test-Kitchen"
    X-Project: "Test-Kitchen"
    X-Termination-Date: "2019-07-20T12:04:30Z"
    X-TTL: 4

transport:
    username: administrator
    ssh_key:  ~\.ssh\id_rsa
    communicator: winrm

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.3

verifier:
  name: inspec
  format: documentation

platforms:
  - name: windows-2012r2
# - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[myiis::server]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
