---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR'] %>
  region: <%= ENV['AWS_REGION'] %>
  security_group_ids: 
    - <%= ENV['AWS_SECURITY_GROUP_ID'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  vpc_id: <%= ENV['AWS_VPC_ID'] %>
  associate_public_ip: true
  instance_type: m3.medium ##t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Chef Training Node for <YOURNAME>, <%= ENV['TRAINER_NAME'] %>"
    created-by: "test-kitchen"
    user: administrator
    X-Contact: <%= ENV['TRAINER_NAME'] %>
    X-Application: "Training"
    X-Dept: "Sales"
    X-Customer: <%= ENV['TRAINER_NAME'] %>
    X-Project: "Student_Lab"
    X-TTL: 4
    
transport:
    username: administrator
    ssh_key:  ~\.ssh\id_rsa
    communicator: winrm

provisioner:
  name: chef_zero
  product_name: chef
  chef_license: accept

verifier:
  name: inspec
  format: documentation

platforms:
  - name: windows-2012r2
# - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[myiis::server]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
